dist: xenial
language: python
python:
 - "3.6"

addons:
  apt:
    packages:
    - python3-dev
    - mosquitto

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
    ./tests/bin/run_all_spacehack_tests -- --verbose --timeout 60

after_success:
  coveralls
